modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Wynd/MineMineNoMi3/issues"

[[mods]]
modId="mineminenomi"
version="0.6.2"
displayName="Mine Mine no Mi"
displayURL="https://www.pixelatedw.xyz/"
logoFile="examplemod.png"
authors="Wynd"
description='''
Mine Mine no Mi is a minecraft mod inspired by the famous anime/manga series One Piece written and illustrated by Eiichiro Oda. It aims to be an adventure oriented mod where exploration is one of the key features.

Dev Team :
	Wynd - Progammer 
	FGpisces - 2D Artist, QA 
	Kenryuu - QA 
	DragonLuch - 3D Artist 
	GeorgeTsakiridis - Programmer 
	Izako - Programmer 
	Zankrid - Programmer

Patreons :
	HypnoMan 
	kiopt 
	Sergio Iucci 
	M4DN3SS 
	Izable 
	å±±åµœã€€
	é †ä¹‹è¼” 
	Beosti 
	TheOmniscientBear 
	Bisky 
	Large Child 
	ğ“œğ“²ğ“·ğ“­ğ“˜ğ“˜ 
	Bluehh 
	SkyKingTv 
	äº•æ“ äº• 
	Lorrain 
	Kiessi 
	Lotus 
	IRuby 
	Yoren Aijin 
	Yohann Rbx 
	Samuel Camas 
	MineZefy 
	Peter La ardilla 
	Butnuster445 
	Noah 
	Gyro 
	Doom

Other Credits :
	CalebBritannia - Programmer 
	KitanicDemon - Builder
	Abelatox - Spanish 
	Ezequiel - Polish 
	Moore5859 (é˜¿çƒ©ä¸¶) - Simplified Chinese 
	Itz Nuk - Brazilian Portuguese 
	Ytekk - French 
	tMakotoi - Russian

'''

[[dependencies.mineminenomi]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mineminenomi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
